In [1]:
import tensorflow as tf

@tf.function
def tf_cube(x):
    return x ** 3

In [2]:
concrete_function = tf_cube.get_concrete_function(tf.constant(2.0))
concrete_function

<ConcreteFunction tf_cube(x) at 0x24BD3D8C5D0>

In [3]:
concrete_function(tf.constant(2.0))


<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [4]:
concrete_function.graph

In [5]:
ops = concrete_function.graph.get_operations()
ops

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'pow/y' type=Const>,
 <tf.Operation 'pow' type=Pow>,
 <tf.Operation 'Identity' type=Identity>]

In [6]:
pow_op = ops[2]
list(pow_op.inputs)

[<tf.Tensor 'x:0' shape=() dtype=float32>,
 <tf.Tensor 'pow/y:0' shape=() dtype=float32>]

In [7]:
pow_op.outputs

[<tf.Tensor 'pow:0' shape=() dtype=float32>]

In [8]:
concrete_function.graph.get_operation_by_name('x')


<tf.Operation 'x' type=Placeholder>

In [9]:
concrete_function.graph.get_tensor_by_name('Identity:0')


<tf.Tensor 'Identity:0' shape=() dtype=float32>

In [10]:
concrete_function.function_def.signature

name: "__inference_tf_cube_7"
input_arg {
  name: "x"
  type: DT_FLOAT
}
output_arg {
  name: "identity"
  type: DT_FLOAT
}

In [11]:
@tf.function
def tf_cube(x):
    print(f"x = {x}")
    return x ** 3

In [12]:
result = tf_cube(tf.constant(2.0))

x = Tensor("x:0", shape=(), dtype=float32)


In [13]:
result

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [15]:
result = tf_cube(tf.constant(3.0))
result


<tf.Tensor: shape=(), dtype=float32, numpy=27.0>

In [16]:
result = tf_cube(tf.constant(4.0))
result

<tf.Tensor: shape=(), dtype=float32, numpy=64.0>

In [17]:
result = tf_cube(2)

x = 2


In [18]:
result = tf_cube(3) 

x = 3


In [19]:
result = tf_cube(tf.constant([[1., 2.]]))

x = Tensor("x:0", shape=(1, 2), dtype=float32)


In [20]:
result = tf_cube(tf.constant([[3., 4.], [5., 6.]]))

x = Tensor("x:0", shape=(2, 2), dtype=float32)


In [21]:
result = tf_cube(tf.constant([[7., 8.], [9., 10.]]))

In [22]:
@tf.function(input_signature=[tf.TensorSpec([None, 28, 28], tf.float32)])
def shrink(images):
    return images[:, ::2, ::2] 

In [24]:
img_batch_1 = tf.random.uniform(shape=[100, 28, 28])
img_batch_2 = tf.random.uniform(shape=[50, 28, 28])
preprocessed_images = shrink(img_batch_1) 
preprocessed_images = shrink(img_batch_2)
preprocessed_images

<tf.Tensor: shape=(50, 14, 14), dtype=float32, numpy=
array([[[0.12546015, 0.38219523, 0.4594289 , ..., 0.82775235,
         0.76100767, 0.8041545 ],
        [0.55816615, 0.08744586, 0.95503664, ..., 0.20777762,
         0.51403403, 0.5605023 ],
        [0.2533077 , 0.2340014 , 0.61998343, ..., 0.09176421,
         0.61981213, 0.969839  ],
        ...,
        [0.45723724, 0.56774426, 0.9768499 , ..., 0.16698492,
         0.8606689 , 0.421306  ],
        [0.95839715, 0.81890786, 0.8259131 , ..., 0.8833375 ,
         0.19251537, 0.5508958 ],
        [0.8564694 , 0.7059337 , 0.57116985, ..., 0.55262613,
         0.6969601 , 0.96161234]],

       [[0.98123074, 0.60876346, 0.5629194 , ..., 0.03055573,
         0.5421611 , 0.70026624],
        [0.49277306, 0.75765705, 0.4568529 , ..., 0.8706111 ,
         0.09664834, 0.11577404],
        [0.24079454, 0.9719763 , 0.47947896, ..., 0.69691277,
         0.39474046, 0.7040695 ],
        ...,
        [0.7488769 , 0.8816974 , 0.97766936, ..., 0.25

In [25]:
img_batch_3 = tf.random.uniform(shape=[2, 2, 2])
preprocessed_images = shrink(img_batch_3)

TypeError: Binding inputs to tf.function failed due to `Can not cast TensorSpec(shape=(2, 2, 2), dtype=tf.float32, name=None) to TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None)`. Received args: (<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0.35066688, 0.8788779 ],
        [0.7720319 , 0.10077572]],

       [[0.5441761 , 0.40873766],
        [0.21864581, 0.78829134]]], dtype=float32)>,) and kwargs: {} for signature: (images: TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None)).

In [26]:
@tf.function
def add_10(x):
    for i in range(10):
        x += 1
    return x


In [27]:
add_10(tf.constant(0))


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [28]:
add_10.get_concrete_function(tf.constant(0)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'add_1/y' type=Const>,
 <tf.Operation 'add_1' type=AddV2>,
 <tf.Operation 'add_2/y' type=Const>,
 <tf.Operation 'add_2' type=AddV2>,
 <tf.Operation 'add_3/y' type=Const>,
 <tf.Operation 'add_3' type=AddV2>,
 <tf.Operation 'add_4/y' type=Const>,
 <tf.Operation 'add_4' type=AddV2>,
 <tf.Operation 'add_5/y' type=Const>,
 <tf.Operation 'add_5' type=AddV2>,
 <tf.Operation 'add_6/y' type=Const>,
 <tf.Operation 'add_6' type=AddV2>,
 <tf.Operation 'add_7/y' type=Const>,
 <tf.Operation 'add_7' type=AddV2>,
 <tf.Operation 'add_8/y' type=Const>,
 <tf.Operation 'add_8' type=AddV2>,
 <tf.Operation 'add_9/y' type=Const>,
 <tf.Operation 'add_9' type=AddV2>,
 <tf.Operation 'Identity' type=Identity>]

In [30]:
@tf.function
def add_10(x):
    for i in tf.range(10):
        x += 1
    return x


add_10.get_concrete_function(tf.constant(0)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'range/start' type=Const>,
 <tf.Operation 'range/limit' type=Const>,
 <tf.Operation 'range/delta' type=Const>,
 <tf.Operation 'range' type=Range>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'floordiv' type=FloorDiv>,
 <tf.Operation 'mod' type=FloorMod>,
 <tf.Operation 'zeros_like' type=Const>,
 <tf.Operation 'NotEqual' type=NotEqual>,
 <tf.Operation 'Cast' type=Cast>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'zeros_like_1' type=Const>,
 <tf.Operation 'Maximum' type=Maximum>,
 <tf.Operation 'while/maximum_iterations' type=Const>,
 <tf.Operation 'while/loop_counter' type=Const>,
 <tf.Operation 'while' type=StatelessWhile>,
 <tf.Operation 'Identity' type=Identity>]

In [31]:
counter = tf.Variable(0)

@tf.function
def increment(counter, c=1):
    return counter.assign_add(c)

increment(counter) 
increment(counter) 

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [32]:
function_def = increment.get_concrete_function(counter).function_def
function_def.signature.input_arg[0]


name: "counter"
type: DT_RESOURCE

In [35]:
counter = tf.Variable(0)

@tf.function
def increment(c=1):
    return counter.assign_add(c)

increment(counter) 

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [36]:
class Counter:
    def __init__(self):
        self.counter = tf.Variable(0)

    @tf.function
    def increment(self, c=1):
        return self.counter.assign_add(c)


In [38]:
# model = MyModel(dynamic=True) 

# class MyDense(tf.keras.layers.Layer):
#     def __init__(self, units, **kwargs):
#         super().__init__(dynamic=True, **kwargs)
#         [...]

# model.compile(loss=my_mse, optimizer="nadam", metrics=[my_mae],run_eagerly=True)

